name: frontend-deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |

          # Установка rsync если не установлен
          if ! command -v rsync &> /dev/null; then
            echo "Устанавливаем rsync..."
            sudo apt-get update
            sudo apt-get install -y rsync
          fi
          
          cd ${{ secrets.REPO_DIR }}
          git pull origin ${{ secrets.BRANCH }}
          npm install --only=prod
          npm run build
          
          echo "=== DRY RUN - проверка изменений в билде labhelp-frontend ==="
          sudo rsync -av --delete --dry-run \
            ${{ secrets.BUILD_DIR }}/ \
            ${{ secrets.TARGET_DIR }}/
          
          echo "=== ВЫПОЛНЯЮ ОБНОВЛЕНИЕ labhelp-frontend ==="
          sudo rsync -av --delete --progress \
            ${{ secrets.BUILD_DIR }}/ \
            ${{ secrets.TARGET_DIR }}/
          
          sudo chown -R ${{ secrets.WEB_USER }}:${{ secrets.WEB_GROUP }} ${{ secrets.TARGET_DIR }}